### PR TITLE
requirement file is added

### PR DESCRIPTION
**Pull request by nishantharde**
bhi tune requirement file nahi add kiya tha

### CODE REVIEW

**Comment by nishantharde** [comment]
for readablity

**Comment by nishantharde** [comment]
plz look at it

**Comment by sonirghv** [comment]
thank you @nishantharde for looking at the requirement file I'll fix it

**Comment by nishantharde** [comment]
you can merge it now

**Comment by nishantharde** [comment]
ok

**Comment by nishantharde** [comment]
.gitignore updated

**Pull request merged**
